### ISSUE TITLE
Always get "price-too-low" for windows platform instance 

### ISSUE THREAD

**Issue by zjd713** [LeanerCloud/AutoSpotting#105]
Always get "price-too-low" for windows platform instance in asg 

Status
price-too-low: Your Spot request price of 0.215 is lower than the minimum required Spot request fulfillment price of 0.2821. 

looks like it can't recognize windows instance.

**Comment by cristim** [comment]
@zjd713 As far as I know Windows is not currently supported, see #32.

Nobody asked for this before so I thought it's not so high priority but now that you noticed this I guess it makes sense to implement it. Adding support for it shouldn't be hard though, I'll look into it within a few days.

**Comment by cristim** [comment]
We should document this as a known issue somewhere, providing a workaround, until it is properly fixed.

**Comment by xlr-8** [comment]
I'm closing this until it is implemented and we actually have some feedback on it.

**Comment by chaud** [comment]
It looks like Windows is potentially maybe supported now, but this issue still exists. The correct spot Windows price is pulled, but it is being compared against the Linux on-demand price. 

At a glance, it seems like the on demand price is still hard coded to Linux here: https://github.com/AutoSpotting/AutoSpotting/blob/master/core/region.go#L206

**Comment by cristim** [comment]
Thanks, looks like you are right. Only the spot pricing is configurable, the on demand price is hard-coded to Linux.

As a workaround if the comparisons fail, you can either set the on demand price multiplier to some value that brings the resulting on demand Linux price close to the Windows price.

Alternatively you can use the aggressive bidding policy which is ignoring the on demand price and just bids a percentage over the current spot price.

**Comment by tapirs** [comment]
@cristim @zjd713 PR #423 should help with this, with this issue, although it looks like the windows premium is variable you should be able to set it to a value which will allow you to spin up windows spot instances.

**Comment by cristim** [comment]
The Spot Product is now configurable, this should no longer be an issue.
