### ISSUE TITLE
Remove autoscaling:DescribeTags permission

### ISSUE THREAD

**Issue by gabegorelick** [LeanerCloud/AutoSpotting#374]
## Issue type ##

Feature Idea

## Summary ##

`scanForEnabledAutoScalingGroupsByTag` was removed in https://github.com/AutoSpotting/AutoSpotting/pull/209, but AutoSpotting still grants `autoscaling:DescribeTags`. As far as I can tell, nothing calls `autoscaling.DescribeTags` anymore since `DescribeAutoScalingGroups` is used instead.

**Comment by cristim** [comment]
Good catch, I think this permission can be removed.
