### ISSUE TITLE
Fix coveralls

### ISSUE THREAD

**Issue by gabegorelick** [LeanerCloud/AutoSpotting#400]
# Github issue #

## Issue type ##

- Bug Report

## Build number #
master

## Summary ##

Coveralls testing of PRs has not been working for some time. Should it be fixed, or removed entirely?

![image](https://user-images.githubusercontent.com/610129/73306223-c403f300-41e9-11ea-9afe-720f4028a291.png)

## Steps to reproduce ##

Open a PR. Notice coveralls results stay pending indefinitely.

## Expected results ##

Coveralls runs. Or coveralls check is removed.

## Actual results ##

Coveralls never runs.

**Comment by cristim** [comment]
This is a known issue, caused by the fact that it needs some secrets only available to PRs created by myself.

I would like to keep it, I hope we can find a way to make it work for everyone else.

**Comment by cristim** [comment]
I'm no longer using coveralls, closing this issue.
