### ISSUE TITLE
OnDemandPercentageAboveBaseCapacity

### ISSUE THREAD

**Issue by gabegorelick** [LeanerCloud/AutoSpotting#403]
# Github issue #

## Issue type ##

- Feature Idea

## Summary ##

AutoSpotting supports a `MinOnDemandNumber` and `MinOnDemandPercentage`, but these are mutually exclusive (`MinOnDemandNumber` takes precedence over `MinOnDemandPercentage`).

In contrast, AWS's native mixed auto scaling groups accept an `OnDemandBaseCapacity` (which is basically identical to `MinOnDemandNumber`) and an `OnDemandPercentageAboveBaseCapacity`. `OnDemandPercentageAboveBaseCapacity` allows you to specify the percentage of instances out of DesiredSize - OnDemandBaseCapacity to be fulfilled with on-demand instances.

See https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_InstancesDistribution.html

It may also make sense to support `OnDemandBaseCapacity` as an alias of `MinOnDemandNumber` to align with AWS's terminology.

## Steps to reproduce ##

Attempt to set a base number of on-demand instances + a percentage of remaining instances to be on-demand.

## Expected results ##

Base number of on-demand instances + percentage of remaining instances are on-demand.

## Actual results ##

Base number of on-demand instances and all remaining are spot.

**Comment by cristim** [comment]
@gabegorelick is this still of interest to you?

**Comment by gabegorelick** [comment]
@cristim Not at the moment. I no longer work with spot instances.

**Comment by cristim** [comment]
Thanks @gabegorelick! In that case I'll close it.
