### ISSUE TITLE
Move code out of autospotting.go

### ISSUE THREAD

**Issue by gabegorelick** [LeanerCloud/AutoSpotting#406]
# Github issue #

## Issue type ##

- Feature Idea

## Summary ##

There's currently no good way to (unit) test code in the file `autospotting.go` (please correct me if I'm wrong!) since that's in the `main` package. We should move as much functionality as we can out of this file so that all the business logic can be tested by unit tests.

This is especially important with changes like #354 changing a lot of code in `autospotting.go` but lacking test coverage.

**Comment by cristim** [comment]
I'm not sure this is still relevant, the code was pretty much rewritten since this issue was raised.

autospotting.go now just defines the Lambda handler and some initialization code. Not sure we need unit tests for that.
